[package]
name = "pdb-addr2line"
version = "0.1.0"
authors = ["Jeff Muizelaar <jrmuizel@gmail.com>", "Markus Stange <mstange.moz@gmail.com>"]
edition = "2018"

[dependencies]
pdb = "0.7.0"

[dev-dependencies]
getopts = "0.2.21"
msvc-demangler = "0.8.0"

